### ISSUE TITLE
mispelling in README.md - `keys` instead of `key`

### ISSUE THREAD

**Issue by zeigerpuppy** [rchaput/acronymsdown#1]
the acronyms definition shown in the README.md should be:

(`keys` instead of `key`)

```yaml
---
acronyms:
  keys:
    - shortname: Rmd
      longname: RMarkdown
    - shortname: YAML
      longname: YAML Ain't Markup Language
---
```

NOT 

```yaml
---
acronyms:
  key:
    - shortname: Rmd
      longname: RMarkdown
    - shortname: YAML
      longname: YAML Ain't Markup Language
---
```

Mispelling will result in error when trying to use acronym:

```
[WARNING][acronymsdown] Acronym key Rmd not recognized
```
