### ISSUE TITLE
inline LaTeX math not parsed properly - how to quote literal for longname?

### ISSUE THREAD

**Issue by zeigerpuppy** [rchaput/acronymsdown#4]
In the RMarkdown document, the following inline parses properly (in both HTML and PDF formats):

```md
$\color{DarkGreen}{\text{Green Text}}$
```

However, when trying to use the same in an acronym:

```yaml
---
acronyms:
  keys:
    - shortname: myacr
      longname: $\color{DarkGreen}{\text{Green Text}}$
---

\acr{myacr}

```

this gets parsed in LaTeX as:

```latex
\textbackslash color\{DarkGreen\}\{\textbackslash text\{Green Text\}\}
```

It looks like the backslash gets converted to a `\textbackslash` which results in the LaTex not working.

whereas it should be parsed as

```
\(\color{DarkGreen}{\text{Green Text}}\)
```

Also tried following without success
- `\color{DarkGreen}{\text{Green Text}}`
- `"\color{DarkGreen}{\text{Green Text}}"`
- `\\color{DarkGreen}{\text{Green Text}}`
- `\(\color{DarkGreen}{\text{Green Text}}\)`

Is there a way to force `\acr{}` to insert literal?
